// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipgbbyvrmpvcboqrjbcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwZ2JieXZybXB2Y2JvcXJqYmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTczMjcsImV4cCI6MjA1NzczMzMyN30.ELHqD5tobPlyPuVgjr_37f6q3V-qDqs3SEV5vamjXVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);